// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceezsvbyqfpjwryiiyet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZXpzdmJ5cWZwandyeWlpeWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDIwMTQsImV4cCI6MjA3MTYxODAxNH0.E6QtrQe8bjLYH-cnV9NYfZ9XryXvPWR14IpP3hopiLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});